### ISSUE TITLE
PelletTop 

### ISSUE THREAD

**Issue by NicetoHave101** [LavermanJJ/home-assistant-solarfocus#86] opened 2023-10-19 19:55 UTC
Hello, have a pellet Top 25. can you integrate this boiler type? A few points I can use right now. For example, the buffer temps. As for the boiler directly, does not work as expected.

Greetings from the Black Forest

**Comment by LavermanJJ** [comment] 2023-10-19 20:53
Look at #48 for reference

**Comment by NicetoHave101** [comment] 2023-10-20 11:32
Unfortunately I have no idea how you could support. attached a screenshot of all values. Buffer sensor, boiler sensor and heating circuit are working. Everything that has to do with the boiler is wrong or is not displayed.

[https://ibb.co/B3pzptQ](url)

**Comment by LavermanJJ** [comment] 2023-10-20 13:38
Did you try both types of biomass boilers when configuring the integration?
![image](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/12856211/ef26df3d-6b76-485f-a0a6-fb4386b7345e)

**Comment by LavermanJJ** [comment] 2023-10-20 13:57
From what I understand it seems that your pelletsboiler does not provide the usual values for biomass boilers. 
You can write an email to Solarfocus asking them whether your appliance supports the "Kessel" section in the eco manager touch Modbus TCP section.

**Comment by NicetoHave101** [comment] 2023-10-20 14:10
I will do it, but I assume that he can.
![Unbenannt](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/148382962/7dbb4b5d-1c35-4785-8417-4dc6010e23e6)

**Comment by LavermanJJ** [comment] 2023-10-20 16:49
Looks like it. Then Solarfocus may be of help to tell the addresses of the input registers, as they are obviously not as declared in their general modbus documentation.

**Comment by leardinet** [comment] 2023-10-26 17:37
Hi everyone, on Monday 30/10/2023 they will come to turn on my Pellet Top for the first time, I would like to understand what to ask the solarfocus technician to have integration with HA. Thanks you need to access the TCP and then what else to do????

Thank you

**Comment by NicetoHave101** [comment] 2023-10-27 20:08
Hey, if TCP is enabled and your kettle is on the network, then you actually have everything. I need an update from my PelletTop. But I can not get a firmware update. I take care of my boiler myself and Solarfocus doesn't give it to me easily. But I don't call a service technician just for an update.
----------------------------------------------------------------------------------------------------------------------------------

Hey, wenn TCP aktiviert ist und dein Kessel im Netzwerk ist, dann hast du eigentlich alles. Ich brauche ein Update von meinem PelletTop. Komme aber nicht an ein Firmware Update ran. Ich kümmere mich selber um meinen Kessel und Solarfocus gibt es mir nicht einfach. Nur für ein Update hole ich aber nicht extra einen Servicetechniker.

**Comment by LavermanJJ** [comment] 2023-10-29 10:59
@leardinet it would be great if you could feedback once set up, if everything works as expected (also what your firmware version is) so that I can update the supported appliances 😉 thanks!

**Comment by leardinet** [comment] 2023-10-30 16:36
> @leardinet it would be great if you could feedback once set up, if everything works as expected (also what your firmware version is) so that I can update the supported appliances 😉 thanks!

Hi, finally installed.
PelletTop firmware ver. V 23.091
I attach what I see in HA
PS. thermostat sensor -270c° I have non-solarfocus thermostats

![1](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/28339407/63d85886-880d-4e5b-a099-47a09d91896e)
![2](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/28339407/493461bf-f5bf-448a-8955-fc16b3c3a44d)
![3](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/28339407/8341fe7e-24a4-43d8-b5ca-40d4cd7e5722)

**Comment by LavermanJJ** [comment] 2023-10-30 16:56
Thanks for sharing! As a quick fix you can simply disable the sensors which are not available within your system.
If some of the sensors do never occur in a Pellettop system I could also introduce a dedicated config.

**Comment by leardinet** [comment] 2023-10-30 18:08
> Grazie per la condivisione! Come soluzione rapida puoi semplicemente disabilitare i sensori che non sono disponibili nel tuo sistema. Se alcuni sensori non si verificano mai in un sistema Pellettop, potrei anche introdurre una configurazione dedicata.

I don't know if it's 
a bug if I activate ModBus communication
in the mysolarfocus app it gives me a problem and it doesn't give me a correct display

1.Modbus Active, no icons appear
![pro](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/28339407/079bf0d2-eaab-4878-872f-8c40128d4f26)

2. Modbus deactivated icons appear correctly
![photo_2023-10-30_19-08-24](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/28339407/794fe4d3-3d34-46f3-a927-bf6e7f80b3fb)

**Comment by LavermanJJ** [comment] 2023-11-01 07:39
This seems to be a bug in Solafocus' App and unrelated to this integration. I'd report it to Solarfocus. Could also be by design?

**Comment by leardinet** [comment] 2023-11-01 11:50
> This seems to be a bug in Solarfocus' App and unrelated to this integration. I'd report it to Solarfocus. Could also be by design?

I managed to get an email from an internal developer at solarfocus, where I reported the matter and asked for other updates related to the app

**Comment by NicetoHave101** [comment] 2023-11-16 06:42
Hey, 
I have received an update from Solarfocus. V23.091
I am now receiving data from the boiler.
Thank you very much

**Comment by LavermanJJ** [comment] 2023-11-16 07:25
Thanks for the update. Can we close the issue then?

**Comment by NicetoHave101** [comment] 2023-11-16 07:29
I'll say yes

**Closed** 2023-11-16 09:09 UTC
